name: Bruin action CI
on:
  push:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: NPM install
        run: npm install
      - name: Unit Test
        run: npx jest
      - name: NPM Build
        run: npm run build 


